# -*- coding: utf-8 -*-
"""NFL_MockDraft

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_1mFThzL2pI1f4JzC-LoKGzrCOTf1CjU
"""

from numpy import True_
import pandas as pd

try:
  Draft_Profiles = pd.read_csv('2023 Prospect Age Database.csv') #reads in csv as Data Frame
except FileNotFoundError:
  print("File not found. Make sure you have the correct files mounted!")
try:
  Teams = pd.read_csv('NFL_Teams.csv')
except FileNotFoundError:
  print("File not found. Make sure you have the correct files mounted!")


#removing unecessary data/cleaning
drop_col = []
for col in Teams.columns:
  if col != "Team" and col != "Priority" and col != "Second Priority" and col != "Selected Player":
    drop_col.append(col)
Teams = Teams.drop(columns=drop_col)

print("Please enter your team")
userTeam = str(input())


#returns Team they selected and the position in which the team picks
print("Your team will draft soon!")
item = Teams[(Teams['Team'] == userTeam)]




i = 0
for team in range(len(Teams)):
  if userTeam == Teams.values[team][0]:
      print("Top players left on the board: \n")
      topPlayers = Draft_Profiles.sort_values(by=['Rank'], ascending = True).head(10)
      print(topPlayers)
      print("\nMake your player selection:",end= " ")
      userPick = str(input())
      for player in range(len(Draft_Profiles)):
        if userPick == Draft_Profiles.values[player][1]:
          print(userTeam + " Have selected " + userPick)
          Draft_Profiles = Draft_Profiles.drop(Draft_Profiles.index[player], inplace = False)
          break
  else:
    for player in range(len(Draft_Profiles)):
      if Teams.values[team][1] == Draft_Profiles.values[player][3] or Draft_Profiles.values[player][3] == Teams.values[team][2]:
        curr = Draft_Profiles.values[player]
        print(curr[1],end=" ")
        print("-----",end=" ")
        print(Teams.values[team][0])
        Teams.values[team][1] = Teams.values[team][2] 
        Draft_Profiles = Draft_Profiles.drop(Draft_Profiles.index[player], inplace = False)
        break